const Action_Types =  {
    FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    FETCH_CURRENT_USER_REQUEST: "FETCH_CURRENT_USER_REQUEST",
    FETCH_CURRENT_USER_SUCCESS: "FETCH_CURRENT_USER_SUCCESS",
    FETCH_CURRENT_USER_FAILURE: "FETCH_CURRENT_USER_FAILURE"
}

export default Action_Types;

