const Action_Types =  {
    FETCH_GADGETS_REQUEST: "FETCH_GADGETS_REQUEST",
    FETCH_GADGETS_SUCCESS: "FETCH_GADGETS_SUCCESS",
    FETCH_GADGETS_FAILURE: "FETCH_GADGETS_FAILURE",

    SEARCH_GADGETS_REQUEST: "SEARCH_GADGETS_REQUEST",
    SEARCH_GADGETS_SUCCESS: "SEARCH_GADGETS_SUCCESS",
    SEARCH_GADGETS_FAILURE: "SEARCH_GADGETS_FAILURE",
}

export default Action_Types;

